command_timeout = 1000

[aws]
disabled = true

[cmd_duration]
disabled = false
format = "[(took $duration)](blue)"

[directory]
truncation_symbol = "â€¦/"
truncate_to_repo = false
style = "green"

[gcloud]
disabled = true

[git_branch]
symbol = "î‚ "
format = "[$symbol$branch](dimmed cyan)"

[git_status]
stashed = ""
modified = "*"
diverged = "â‡¡â‡£"
format = "[$all_status](dimmed cyan)[$ahead_behind](dimmed cyan) "

[hostname]
ssh_only = true
trim_at = ""
format = "@[$hostname](bold yellow) "

[nodejs]
symbol = "ðŸ–§ "

[package]
disabled = true

[status]
disabled = false

[username]
format = "[$user](bold yellow)"
