command_timeout = 1000

[aws]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = false
format = "[(took $duration)](blue)"

[directory]
truncation_symbol = "…/"
truncate_to_repo = false
style = "green"

[gcloud]
disabled = true

[git_branch]
symbol = ""
format = "[$symbol$branch](dimmed cyan)"

[hostname]
ssh_only = true
trim_at = ""
format = "@[$hostname](bold yellow) "

[status]
disabled = false

[username]
format = "[$user](bold yellow)"
